psyApps/apps/urls.py
from django.conf import settings
from django.urls import path, include

from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('patient', views.PatientView.as_view(), name="patient"),
    path('login', views.LoginView.as_view(), name="login"),
    path('logout', views.LogoutView.as_view(), name="logout"),
    path('api/', include(('apps.api_urls', 'api'), namespace='api')),
]

psyApps/psyApps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('apps/', include(('apps.urls', 'apps'), namespace='apps')),
    path('admin/', admin.site.urls),
]

psyApps/apps/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Patient(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Contact")
    MISTER = 'MR'
    MISS = 'MISS'
    MISSES = 'MRS'
    GENDER = (
        (MISTER, 'Monsieur'),
        (MISS, 'Mademoiselle'),
        (MISSES, 'Madame'),
    )
    gender = models.CharField(
        max_length=4, choices=GENDER, default=MISTER, verbose_name="Civilité")
    last_name = models.CharField(max_length=50, verbose_name="Nom")
    first_name = models.CharField(max_length=50, verbose_name="Prénom")
    phone = models.CharField(max_length=10, verbose_name="Téléphone")

    def __str__(self):
        return self.last_name + " " + self.first_name

    class Meta:
        verbose_name = "Patient"

    @property
    def get_address(self):
        patient_address = Address.objects.filter(patient_id=self.id)
        return patient_address

    @property
    def get_subjects(self):
        patient_subjects = Subject.objects.filter(patient_id=self.id)
        return patient_subjects


class Address(models.Model):
    patient_id = models.ForeignKey(
        Patient, on_delete=models.CASCADE, verbose_name="Patient")
    address = models.CharField(max_length=255, verbose_name="Adresse")
    additional_address = models.CharField(
        max_length=255, blank=True, verbose_name="Complément d'adresse")
    postcode = models.CharField(max_length=5, verbose_name="Code postal")
    city = models.CharField(max_length=50, verbose_name="Ville")

    class Meta:
        verbose_name = 'Adresse'
        verbose_name_plural = 'Adresses'

    def __str__(self):
        return self.patient_id.first_name + " " + self.patient_id.last_name + " (" + self.address + ", " + self.postcode + " " + self.city + ")"


class Subject(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now_add=True)
    patient_id = models.ForeignKey(
        Patient, on_delete=models.CASCADE, verbose_name="Patient")
    title = models.CharField(
        max_length=50, blank=True, verbose_name="Titre")
    LOW = 'L'
    MEDIUM = 'M'
    HIGHT = 'H'
    LEVEL = (
        (LOW, 'Bas'),
        (MEDIUM, 'Moyen'),
        (HIGHT, 'Urgent'),
    )
    level = models.CharField(
        max_length=4, choices=LEVEL, default=LOW, verbose_name="Criticité")

    class Meta:
        verbose_name = 'Sujet'

    def __str__(self):
        return self.patient_id.first_name + " " + self.patient_id.last_name + " (" + self.title + ")"

    @property
    def get_messages(self):
        subject_detail = Message.objects.filter(subject_id=self.id)
        return subject_detail


class Message(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    subject_id = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Sujet")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Auteur", null=True)
    message = models.CharField(max_length=1000, verbose_name="Message")

    class Meta:
        verbose_name = 'Message'

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " (" + self.subject_id.title + ")"

psyApps/apps/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.forms.widgets import TextInput, PasswordInput, Textarea, Widget
from django.utils.safestring import mark_safe

from apps.models import Subject


class TextareaWidget(Widget):

    def __init__(self, base_widget, data, *args, **kwargs):
        """Initialise widget and get base instance"""
        super(TextareaWidget, self).__init__(*args, **kwargs)
        self.base_widget = base_widget(*args, **kwargs)
        self.data = data

    def render(self, name, value, attrs=None, renderer=None):
        """Render base widget and add bootstrap spans"""
        field = self.base_widget.render(name, value, attrs)
        return mark_safe((
            '<div class="form-floating mb-3">'
            # '  <div class="input-group-prepend">'
            # '    <span class="input-group-text">Message</span>'
            # '  </div>'
            '  <textarea name="message" rows="5" cols="20" class="form-control" placeholder="Votre message" aria-label="Message" required=True></textarea>'
            '  <label for="floatingInput">Votre message</label>'
            '</div>'
        ) % {'field': field, 'data': self.data})


class UserForm(Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ['id', 'title', 'level']
        extra = 1


class MessageForm(Form):
    message = forms.CharField(
        required=True,
        widget=TextareaWidget(base_widget=Textarea, data='$'),
        label="",
    )

psyApps/apps/views.py
from django.forms.models import ModelForm
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction

from apps.forms import UserForm, SubjectForm, MessageForm
from apps.models import Patient, Subject, Message


def index(request):

    return render(request, 'apps/index.html')


class PatientView(TemplateView):
    template_name = 'apps/patient.html'
    # form_class = SubjectForm
    # success_url = reverse_lazy('apps')
    # success_message = "Way to go!"

    def get(self, request):
        MForm = MessageForm()
        patient = Patient.objects.filter(user_id=request.user.id).first()
        context = {
            'patient': patient,
            'MForm': MForm,
        }

        return render(request, 'apps/patient.html', context)

    def post(self, request):
        MForm = MessageForm(request.POST)
        subject_id = request.POST.get('subject_id')
        subject = get_object_or_404(Subject, id=subject_id)
        if MForm.is_valid():
            with transaction.atomic():
                message = Message()
                message.subject_id = subject
                message.message = MForm.cleaned_data.get('message')
                message.user = request.user
                # message.save()
        else:
            error = "une erreur est survenue"

        patient = Patient.objects.filter(user_id=request.user.id).first()
        context = {
            'patient': patient,
            'MForm': MForm,
            'subject_id': int(subject_id),
        }

        return render(request, 'apps/patient.html', context)


class LoginView(TemplateView):

    template_name = 'apps/login.html'
    context = {}

    def post(self, request, **kwargs):
        UForm = UserForm(data=request.POST)
        if UForm.is_valid():
            username = UForm.cleaned_data['username']
            password = UForm.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return render(request, 'apps/index.html')
            else:
                error_message = "Identifiant ou mot de passe incorrect."
                messages.error(request, error_message)

        context = {'UForm': UForm}

        return render(request, self.template_name, context)

    def get(self, request):
        UForm = UserForm()
        context = {'UForm': UForm}

        return render(request, self.template_name, context)


# @login_required
class LogoutView(TemplateView):

    template_name = 'apps/index.html'

    def get(self, request):

        logout(request)

        return render(request, self.template_name)

psyApps/apps/templates/apps/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% include 'apps/head.html' %}
    </head>
    <body>
        <header>
            {% include 'apps/header.html' %}
        </header>
        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<footer>
            {% include 'apps/footer.html' %}
        </footer>
    </body>

psyApps/apps/templates/apps/footer.html
<div>
    <p>Footer</p>
</div>

psyApps/apps/templates/apps/head.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

psyApps/apps/templates/apps/header.html
<div>
    {% if user.is_authenticated %}
    <div>
        <div>{{ user.username }}</div>
        <ul>
            <li><a  href="{% url 'apps:index' %}">Accueil</a></li>
            <li><a  href="{% url 'apps:patient' %}">Profil</a></li>
            <li><a  href="{% url 'apps:logout' %}">Déconnexion</a></li>
        </ul>
    </div>
    {% else %}
        <a href="{% url 'apps:login' %}">
            <button type="submit">
                <i class="bi bi-box-arrow-right me-1"></i>
                Se Connecter
            </button>
        </a>
    {% endif %}
</div>

psyApps/apps/templates/apps/index.html
{% extends 'apps/base.html' %}

{% block content %}
    <p>Accueil</p>
{% endblock %}

psyApps/apps/templates/apps/item_accordion.html
<div class="accordion accordion-flush" id="{{ accordionId }}">
    {% for item in list %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading{{ item.id }}">
                <button class="accordion-button {% if item.id == item_actived %}{% else %} collapsed {% endif %}" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse{{ item.id }}" aria-expanded="{% if item.id == item_actived %} true {% else %} false {% endif %}" aria-controls="collapse{{ item.id }}">
                    {% block accordion_title %}{% endblock %}
                </button>
            </h2>
            <div id="collapse{{ item.id }}" class="accordion-collapse collapse {% if item.id == item_actived %} show {% else %} {% endif %}"
                    aria-labelledby="heading{{ item.id }}" data-bs-parent="#{{ accordionId }}">
                <div class="accordion-body">
                    {% block accordion_body %}{% endblock %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

psyApps/apps/templates/apps/item_alert.html
<div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
  </div>

psyApps/apps/templates/apps/login.html
{% extends 'apps/base.html' %}
{% load bootstrap5 %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% include "apps/item_alert.html" %}
        {% endfor %}
    {% endif %}
    <div>
        <form action="{% url 'apps:login' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form UForm %}
            <button type="submit">Log In</button>
        </form>
    </div>
{% endblock %}

psyApps/apps/templates/apps/patient.html
{% extends 'apps/base.html' %}

{% block content %}
    {% include "apps/subjects.html" with list=patient.get_subjects item_actived=subject_id accordionId='accordionSubject' %}
{% endblock %}

psyApps/apps/templates/apps/subjects.html
{% extends 'apps/item_accordion.html' %}
{% load bootstrap5 %}


{% block accordion_title %}
    {{ item.id }} - {{ item.title }}
{% endblock %}

{% block accordion_body %}
    {% for message in item.get_messages %}
        <p>{{ message.created_at }} - {{ message.user.username }} - {{ message.message }}</p>
    {% endfor %}
    <form action="{% url 'apps:patient' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="subject_id" value="{{ item.id }}" >
        {% bootstrap_form MForm %}
        <button type="submit">Envoyer</button>
    </form>
{% endblock %}